import Footer from '@/components/Footer';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import { ApolloWrapper } from './ApolloWrapper';
import { ThemeProvider } from 'next-themes';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.variable} antialiased`}>
        <ApolloWrapper>
          <ThemeProvider>
            <div className="min-h-screen flex flex-col justify-between font-sans">
              <Header />
              {children}
              <Footer />
            </div>
          </ThemeProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
